### PR TITLE
Merge back to saasbook

### PR DESCRIPTION
**Pull request by adamtau**
Ready:
API endpoints and their corresponding JSON/JPG response

### CODE REVIEW

**Comment by an-ju** [comment]
ZenTest (= 4.11.0) depends on a rubygems version < 3.0.  Can you consider upgrading ZenTest?

**Comment by an-ju** [comment]
Also, your Gemfile depends on bundler < 2.0.  Please consider upgrading the dependencies.

**Comment by an-ju** [comment]
The app can be set up, but the README is unclear.  Please update README to list the endpoints.  Besides, please explain in the README how the app should be connected to CalCentral.

**Comment by an-ju** [comment]
Cucumber and Rspec tests fail.  Please fix the tests.

Cucumber output
```
Failing Scenarios:
cucumber features/advisor_act_as.feature:9 # Scenario: Access /advisor_act_as
cucumber features/my_finaid_profile.feature:9 # Scenario: Access /api/my/finaid_profile/2018
cucumber features/rosters_campus_campus_course_id.feature:9 # Scenario: Access /api/academics/rosters/campus/1
```

Rspec output
```
An error occurred while loading ./spec/controllers/apis_controller_spec.rb.
Failure/Error:
  RSpec.describe ApisController, type: :controller do

    # This should return the minimal set of attributes required to create a valid
    # Api. As you add validations to Api, be sure to
    # adjust the attributes here as well.
    let(:valid_attributes) {
      skip("Add a hash of attributes valid for your model")
    }

    let(:invalid_attributes) {

NameError:
  uninitialized constant ApisController
# ./spec/controllers/apis_controller_spec.rb:26:in `<top (required)>'

An error occurred while loading ./spec/models/api_spec.rb.
Failure/Error:
  RSpec.describe Api, type: :model do
    pending "add some examples to (or delete) #{__FILE__}"
  end

NameError:
  uninitialized constant Api
# ./spec/models/api_spec.rb:3:in `<top (required)>'

An error occurred while loading ./spec/routing/apis_routing_spec.rb.
Failure/Error:
  RSpec.describe ApisController, type: :routing do
    describe "routing" do

      it "routes to #index" do
        expect(:get => "/apis").to route_to("apis#index")
      end

      it "routes to #new" do
        expect(:get => "/apis/new").to route_to("apis#new")
      end

NameError:
  uninitialized constant ApisController
# ./spec/routing/apis_routing_spec.rb:3:in `<top (required)>'


Finished in 0.0005 seconds (files took 1.84 seconds to load)
0 examples, 0 failures, 3 errors occurred outside of examples
```

**Comment by an-ju** [comment]
Required actions

-  Update README to explain the setup with CalCentral.
-  Update README to list the main endpoints (eg. /api, an example of the stubbed API).
-  Fix Cucumber and rspec tests.  You should try to set it up in a clean environment.

**Comment by XiaochenH** [comment]
Cucumber and Rspec tests are fixed, the failing tests were due to changes to several variable names that weren't reflected in the specs

**Comment by Eric-Le-Ge** [comment]
Hi An, please verify that all issues listed are addressed. Thank you!

**Comment by an-ju** [comment]
The updates look good. 

I didn't notice but please remove the /tmp folder and the db/*.sqlite files from the repository.  You can put an empty .keep file under /tmp folder to keep the folder structure.  However, the temporary files shouldn't be tracked.

**Comment by an-ju** [comment]
BTW, no need to worry about passing the deadline.

**Pull request merged**
